name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Setup AWS CLI
        run: aws configure set aws_access_key_id AKIAULQET33SHGJAHWFG && aws configure set aws_secret_access_key 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 && aws configure set region us-east-1

      - name: Sync to S3
        run: aws s3 cp VK-website.png s3://vk-bucket1/

